name: Build Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o libtest.so -buildmode=c-shared main.go
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o libtest.dll -buildmode=c-shared main.go
        shell: bash
        if: matrix.os == 'windows-latest'

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o libtest.dylib -buildmode=c-shared main.go
        shell: bash
        if: matrix.os == 'macos-latest'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libraries
          path: |
            libtest.so
            libtest.dll
            libtest.dylib